import type { components } from './schema'

// Raccourcis vers les types générés depuis l'OpenAPI du backend (npm run api:generer) :
// aucun type de l'API n'est écrit à la main.
type Schemas = components['schemas']

export type ReponseConnexion = Schemas['ReponseConnexion']
export type ReponseRafraichissement = Schemas['ReponseRafraichissement']
export type ReponseMoi = Schemas['ReponseMoi']
export type EntrepriseAccessible = Schemas['EntrepriseAccessible']
export type ConfigurationPublique = Schemas['ConfigurationPublique']
export type DemandeConnexion = Schemas['DemandeConnexion']
export type DemandeInscription = Schemas['DemandeInscription']
export type DemandeCreationEntreprise = Schemas['DemandeCreationEntreprise']
export type EntrepriseCreee = Schemas['EntrepriseCreee']
export type EntreprisePlateforme = Schemas['EntreprisePlateforme']
export type PageEntreprisesPlateforme = Schemas['PageResultatsEntreprisePlateforme']
export type EtablissementResume = Schemas['EtablissementResume']
export type PageEtablissements = Schemas['PageResultatsEtablissementResume']
export type DemandeEtablissement = Schemas['DemandeEtablissement']
export type DemandeModificationEtablissement = Schemas['DemandeModificationEtablissement']
export type Portee = ReponseMoi['portee']
export type EmployeResume = Schemas['EmployeResume']
export type AffectationEmploye = Schemas['AffectationEmploye']
export type ResultatEmploye = Schemas['ResultatEmploye']
export type RoleAttribuable = Schemas['RoleAttribuable']
export type PageEmployes = Schemas['PageResultatsEmployeResume']
export type DemandeEmploye = Schemas['DemandeEmploye']
export type DemandeModificationEmploye = Schemas['DemandeModificationEmploye']
export type DemandeChangementMotDePasse = Schemas['DemandeChangementMotDePasse']
export type AppareilCourant = Schemas['AppareilCourant']
export type AppareilResume = Schemas['AppareilResume']
export type PageAppareils = Schemas['PageResultatsAppareilResume']
export type CodeGenere = Schemas['CodeGenere']
export type StatutCode = Schemas['StatutCode']
