/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/appareil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconnaître cette tablette
         * @description Avec le cookie « appareil ». Erreur : NON_AUTHENTIFIE (401) si la tablette n'est pas enregistrée, ou a été révoquée : elle affiche alors l'écran d'enregistrement.
         */
        get: operations["courant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareil/appairage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enregistrer cette tablette avec le code du gérant
         * @description Pose le cookie HttpOnly « appareil ». Exige l'en-tête X-Demande-Tonti: 1 et une origine autorisée. Erreurs : CODE_APPAIRAGE_INVALIDE (inconnu, expiré ou déjà utilisé), TROP_DE_TENTATIVES (Retry-After).
         */
        post: operations["appairer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareil/connexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prendre la caisse avec son PIN
         * @description PIN_A_CHANGER si le code saisi est le PIN temporaire : l'employé choisit le sien (POST /appareil/pin). Erreurs : PIN_INCORRECT (401), PROFIL_BLOQUE (423, au 5e code erroné : un gérant réinitialise le PIN), RESSOURCE_INTROUVABLE (employé absent de cette tablette), TROP_DE_TENTATIVES (Retry-After).
         */
        post: operations["prendre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareil/personnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qui peut prendre cette caisse
         * @description Employés actifs avec un PIN et un rôle dans l'établissement de la tablette (ou toute l'entreprise). Erreur : NON_AUTHENTIFIE (401) si la tablette n'est pas enregistrée.
         */
        get: operations["personnel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareil/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Choisir son PIN et prendre la caisse
         * @description 4 à 6 chiffres, ni suite (1234) ni répétition (1111). Mêmes erreurs que la prise de caisse, plus REQUETE_INVALIDE (champ nouveauPin).
         */
        post: operations["changerPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les tablettes visibles, actives d'abord */
        get: operations["lister_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareils/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Générer un code d'enregistrement de tablette
         * @description Code à 6 chiffres, valable 10 minutes, renvoyé une seule fois. Erreurs : ACCES_REFUSE (établissement hors périmètre), REQUETE_INVALIDE (établissement inconnu).
         */
        post: operations["genererCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareils/codes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suivre un code : en attente, utilisé ou expiré */
        get: operations["statutCode"];
        put?: never;
        post?: never;
        /** Annuler un code encore en attente */
        delete: operations["annulerCode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareils/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Renommer une tablette
         * @description Erreur : CONFLIT_MODIFICATION (409, version dépassée).
         */
        put: operations["renommer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appareils/{id}/revocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Révoquer une tablette
         * @description Son jeton ne vaut plus rien : elle doit être réenregistrée.
         */
        post: operations["revoquer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/connexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Se connecter
         * @description Identifiant : e-mail ou téléphone. Pose le cookie HttpOnly « rafraichissement ». Renvoie un jeton d'accès directement pour un administrateur plateforme ou un compte à une seule entreprise ; pour plusieurs entreprises, aucun jeton : choisir l'entreprise puis appeler /auth/rafraichir avec son entrepriseId. Erreurs : IDENTIFIANTS_INVALIDES, COMPTE_VERROUILLE, TROP_DE_TENTATIVES (Retry-After), AUCUNE_ENTREPRISE, ENTREPRISE_SUSPENDUE.
         */
        post: operations["connecter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/deconnexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Se déconnecter
         * @description Révoque la session (toute la famille de jetons de rafraîchissement) et efface le cookie. Exige l'en-tête X-Demande-Tonti: 1 et une origine autorisée.
         */
        post: operations["deconnecter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/rafraichir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rafraîchir le jeton d'accès ou changer d'entreprise
         * @description Échange le cookie « rafraichissement » contre un nouveau (rotation) et un jeton d'accès pour l'entreprise demandée ou l'entreprise courante. Exige l'en-tête X-Demande-Tonti: 1 et une origine autorisée. Erreurs : SESSION_EXPIREE, ACCES_REFUSE (entreprise étrangère ou requête hors frontend).
         */
        post: operations["rafraichir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/caisse/moi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employé qui tient la caisse, son rôle ici et ses permissions */
        get: operations["moi_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/caisse/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prolonger la session de caisse
         * @description Appelé tant que la caisse sert, avant l'expiration du jeton (15 minutes). NON_AUTHENTIFIE (401) si la tablette a été révoquée, le PIN réinitialisé ou l'employé désactivé : retour à « Qui prend la caisse ? ».
         */
        post: operations["renouveler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/caisse/validateurs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qui peut valider cette action ici
         * @description Employés qui ont la permission dans l'établissement de la tablette, avec un PIN choisi, hors l'employé qui tient la caisse.
         */
        get: operations["validateurs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/caisse/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valider une action sensible avec le PIN d'un gérant
         * @description Valable 60 secondes, une seule fois, pour cette permission, cet objet, cette tablette et l'employé qui tient la caisse. Erreurs : PIN_INCORRECT (401), PROFIL_BLOQUE (423), ACCES_REFUSE (le validateur n'a pas la permission ici), RESSOURCE_INTROUVABLE, TROP_DE_TENTATIVES.
         */
        post: operations["valider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etablissements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les établissements, triés par code */
        get: operations["lister_2"];
        put?: never;
        /**
         * Créer un établissement
         * @description Permission ETABLISSEMENT_GERER. Erreur : CODE_ETABLISSEMENT_DEJA_UTILISE (409).
         */
        post: operations["creer_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etablissements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Modifier un établissement
         * @description Permission ETABLISSEMENT_GERER. Erreurs : RESSOURCE_INTROUVABLE (404), CONFLIT_MODIFICATION (409, version dépassée), CODE_ETABLISSEMENT_DEJA_UTILISE (409).
         */
        put: operations["modifier_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * S'inscrire : créer son entreprise et se connecter
         * @description 404 RESSOURCE_INTROUVABLE si l'inscription est fermée. Si le téléphone ou l'e-mail a déjà un compte, le mot de passe doit être le sien (sinon IDENTIFIANTS_INVALIDES). Même réponse et même cookie que /auth/connexion.
         */
        post: operations["inscrire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compte connecté, entreprise courante et permissions effectives */
        get: operations["moi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moi/mot-de-passe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer son mot de passe
         * @description Obligatoire à la première connexion avec un mot de passe temporaire (compte.motDePasseAChanger) : jusque-là, seuls /moi et ce changement sont permis. Toutes les sessions du compte sont fermées, il faut se reconnecter. Erreurs : REQUETE_INVALIDE (champs motDePasseActuel, nouveauMotDePasse), COMPTE_VERROUILLE.
         */
        post: operations["changerMotDePasse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister le personnel visible : actifs d'abord, par nom */
        get: operations["lister_1"];
        put?: never;
        /**
         * Ajouter un employé
         * @description Renvoie une seule fois le PIN temporaire et, si un compte back-office est créé, le mot de passe temporaire. Erreurs : REQUETE_INVALIDE (affectations, telephone, email), ACCES_REFUSE (établissement hors périmètre, rôle au-delà de ses propres droits).
         */
        post: operations["creer_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Modifier un employé et remplacer ses rôles
         * @description Erreurs : CONFLIT_MODIFICATION (version dépassée), ACCES_REFUSE (hors périmètre, soi-même, propriétaire), REQUETE_INVALIDE.
         */
        put: operations["modifier"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/{id}/desactivation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Désactiver un employé
         * @description Plus de connexion ni de PIN ; ses sessions tombent.
         */
        post: operations["desactiver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Réinitialiser le PIN
         * @description Génère un nouveau PIN temporaire, renvoyé une seule fois.
         */
        post: operations["reinitialiserPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/{id}/reactivation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Réactiver un employé */
        post: operations["reactiver_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plateforme/entreprises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les entreprises, les plus récentes d'abord */
        get: operations["lister"];
        put?: never;
        /**
         * Créer une entreprise, son premier établissement et son propriétaire
         * @description Si le propriétaire a déjà un compte (même téléphone ou e-mail), il est rattaché et garde son mot de passe ; sinon un compte est créé avec un mot de passe temporaire, renvoyé une seule fois (motDePasseTemporaire), que le propriétaire remplacera à sa première connexion.
         */
        post: operations["creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plateforme/entreprises/{id}/reactivation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Réactiver une entreprise suspendue */
        post: operations["reactiver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plateforme/entreprises/{id}/suspension": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspendre une entreprise
         * @description Plus aucune connexion ; les jetons en cours tombent.
         */
        post: operations["suspendre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Réglages publics (sans authentification) */
        get: operations["configuration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rôles système et ceux que la personne connectée peut donner */
        get: operations["roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AffectationEmploye: {
            /** Format: uuid */
            etablissementId?: string;
            role: string;
        };
        AppareilCourant: {
            /** Format: int32 */
            delaiVerrouillageMinutes: number;
            entreprise: components["schemas"]["Entreprise"];
            etablissement: components["schemas"]["Etablissement"];
            /** Format: uuid */
            id: string;
            nom: string;
        };
        AppareilResume: {
            /** Format: date-time */
            derniereActiviteLe?: string;
            /** Format: uuid */
            etablissementId: string;
            /** Format: uuid */
            id: string;
            nom: string;
            revoquee: boolean;
            /** Format: int64 */
            version: number;
        };
        ChampInvalide: {
            champ: string;
            message: string;
        };
        CodeGenere: {
            code: string;
            /** Format: date-time */
            expireLe: string;
            /** Format: uuid */
            id: string;
        };
        ConfigurationPublique: {
            inscriptionOuverte: boolean;
        };
        DemandeAffectation: {
            /** Format: uuid */
            etablissementId?: string;
            /** @example SERVEUR */
            role: string;
        };
        DemandeAppairage: {
            /** @example 482915 */
            code: string;
        };
        DemandeChangementMotDePasse: {
            motDePasseActuel: string;
            nouveauMotDePasse: string;
        };
        DemandeChangementPin: {
            /** @example 4827 */
            nouveauPin: string;
            /** @example 610294 */
            pinActuel: string;
            /** Format: uuid */
            utilisateurId: string;
        };
        DemandeCodeAppairage: {
            /** Format: uuid */
            etablissementId: string;
            /** @example Caisse 1, bar */
            nom: string;
        };
        DemandeConnexion: {
            /** @example 90 11 22 33 */
            identifiant: string;
            motDePasse: string;
            /** @example TG */
            pays?: string;
        };
        DemandeCreationEntreprise: {
            entreprise: components["schemas"]["DonneesEntreprise"];
            etablissement: components["schemas"]["DonneesPremierEtablissement"];
            proprietaire: components["schemas"]["DonneesProprietaire"];
        };
        DemandeEmploye: {
            affectations: components["schemas"]["DemandeAffectation"][];
            email?: string;
            /** @example Agbeko */
            nom: string;
            /** @example Kossi */
            prenom: string;
            /** @example 90 11 23 45 */
            telephone?: string;
        };
        DemandeEtablissement: {
            adresse?: string;
            /** @example BE */
            code: string;
            /**
             * Format: int32
             * @description Minutes sans activité avant le retour à « Qui prend la caisse ? » (3 par défaut)
             * @example 3
             */
            delaiVerrouillageMinutes?: number;
            /** @example Africa/Lome */
            fuseauHoraire: string;
            /** @example Bè Kpota */
            nom: string;
            /** @example Lomé */
            ville?: string;
        };
        DemandeInscription: {
            entreprise: components["schemas"]["DonneesEntreprise"];
            etablissement: components["schemas"]["DonneesPremierEtablissement"];
            proprietaire: components["schemas"]["DonneesProprietaireInscription"];
        };
        DemandeModificationEmploye: {
            affectations: components["schemas"]["DemandeAffectation"][];
            email?: string;
            nom: string;
            prenom: string;
            telephone?: string;
            /** Format: int64 */
            version: number;
        };
        DemandeModificationEtablissement: {
            adresse?: string;
            /** @example BE */
            code: string;
            /**
             * Format: int32
             * @description Minutes sans activité avant le retour à « Qui prend la caisse ? » (3 par défaut)
             * @example 3
             */
            delaiVerrouillageMinutes?: number;
            /** @example Africa/Lome */
            fuseauHoraire: string;
            /** @example Bè Kpota */
            nom: string;
            /** Format: int64 */
            version: number;
            ville?: string;
        };
        DemandePriseDeCaisse: {
            /** @example 4827 */
            pin: string;
            /** Format: uuid */
            utilisateurId: string;
        };
        DemandeRafraichissement: {
            /** Format: uuid */
            entrepriseId?: string;
        };
        DemandeRenommageAppareil: {
            nom: string;
            /** Format: int64 */
            version: number;
        };
        DemandeValidation: {
            /** Format: uuid */
            objetId: string;
            /**
             * @example LIGNE_ANNULER_APRES_ENVOI
             * @enum {string}
             */
            permission: "COMMANDE_CREER" | "LIGNE_ANNULER_APRES_ENVOI" | "TABLE_TRANSFERER" | "REMISE_APPLIQUER" | "REMISE_AU_DELA_PLAFOND" | "ARTICLE_OFFRIR" | "PAIEMENT_ENCAISSER" | "PAIEMENT_REMBOURSER" | "CAISSE_OUVRIR" | "CAISSE_FERMER" | "CAISSE_MOUVEMENT" | "STOCK_RECEPTIONNER" | "STOCK_AJUSTER" | "CATALOGUE_GERER" | "PRIX_MODIFIER" | "RAPPORT_VENTES" | "RAPPORT_FINANCIER" | "CLIENT_CREDIT" | "PERSONNEL_GERER" | "ETABLISSEMENT_GERER" | "BACK_OFFICE" | "APPAREIL_GERER";
            /** @example 5937 */
            pin: string;
            /** Format: uuid */
            validateurId: string;
        };
        DonneesEntreprise: {
            /** @example XOF */
            devise: string;
            /** @example Africa/Lome */
            fuseauHoraire: string;
            /**
             * @example fr
             * @enum {string}
             */
            langue: "fr" | "en";
            /** @example Maquis Chez Tanti */
            nom: string;
            /** @example TG */
            pays: string;
        };
        DonneesPremierEtablissement: {
            adresse?: string;
            /** @example BE */
            code: string;
            /** @example Bè Kpota */
            nom: string;
            /** @example Lomé */
            ville?: string;
        };
        DonneesProprietaire: {
            email?: string;
            /** @example Akouvi */
            nom: string;
            /** @example Tanti */
            prenom: string;
            /** @example +228 90 11 22 33 */
            telephone?: string;
        };
        DonneesProprietaireInscription: {
            email?: string;
            motDePasse: string;
            /** @example Akouvi */
            nom: string;
            /** @example Tanti */
            prenom: string;
            /** @example +228 90 11 22 33 */
            telephone?: string;
        };
        EmployeResume: {
            actif: boolean;
            affectations: components["schemas"]["AffectationEmploye"][];
            backOffice: boolean;
            email?: string;
            gerable: boolean;
            /** Format: uuid */
            id: string;
            nom: string;
            pinAChanger: boolean;
            pinReinitialisable: boolean;
            prenom: string;
            telephone?: string;
            /** Format: int64 */
            version: number;
        };
        Entreprise: {
            /** Format: uuid */
            id: string;
            nom: string;
        };
        EntrepriseAccessible: {
            /** Format: uuid */
            id: string;
            nom: string;
        };
        EntrepriseCourante: {
            devise: string;
            fuseauHoraire: string;
            /** Format: uuid */
            id: string;
            nom: string;
            pays: string;
        };
        EntrepriseCreee: {
            compteExistant: boolean;
            /** Format: uuid */
            etablissementId: string;
            /** Format: uuid */
            id: string;
            motDePasseTemporaire?: string;
            nom: string;
            /** Format: uuid */
            proprietaireCompteId: string;
        };
        EntreprisePlateforme: {
            /** Format: date-time */
            creeLe: string;
            /** Format: uuid */
            id: string;
            nom: string;
            /** Format: int64 */
            nombreEtablissements: number;
            pays: string;
            /** @enum {string} */
            statut: "ACTIVE" | "SUSPENDUE";
        };
        Etablissement: {
            /** Format: uuid */
            id: string;
            nom: string;
            ville?: string;
        };
        EtablissementResume: {
            actif: boolean;
            adresse?: string;
            code: string;
            /** Format: int32 */
            delaiVerrouillageMinutes: number;
            fuseauHoraire: string;
            /** Format: uuid */
            id: string;
            nom: string;
            /** Format: int64 */
            version: number;
            ville?: string;
        };
        PageResultatsAppareilResume: {
            elements: components["schemas"]["AppareilResume"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            taille: number;
            /** Format: int64 */
            total: number;
        };
        PageResultatsEmployeResume: {
            elements: components["schemas"]["EmployeResume"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            taille: number;
            /** Format: int64 */
            total: number;
        };
        PageResultatsEntreprisePlateforme: {
            elements: components["schemas"]["EntreprisePlateforme"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            taille: number;
            /** Format: int64 */
            total: number;
        };
        PageResultatsEtablissementResume: {
            elements: components["schemas"]["EtablissementResume"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            taille: number;
            /** Format: int64 */
            total: number;
        };
        ProfilCaisse: {
            bloque: boolean;
            nomCourt: string;
            pinAChanger: boolean;
            prenom: string;
            role: string;
            /** Format: uuid */
            utilisateurId: string;
        };
        ReponseConnexion: {
            compte: components["schemas"]["ResumeCompte"];
            /** Format: uuid */
            entrepriseCourante?: string;
            entreprises: components["schemas"]["EntrepriseAccessible"][];
            jetonAcces?: string;
        };
        ReponseErreur: {
            champs?: components["schemas"]["ChampInvalide"][];
            code: string;
            details?: {
                [key: string]: Record<string, never>;
            };
            message: string;
            /** Format: int32 */
            statut: number;
            traceId?: string;
        };
        ReponseJetonCaisse: {
            jetonAcces: string;
        };
        ReponseMoi: {
            compte: components["schemas"]["ResumeCompte"];
            entrepriseCourante?: components["schemas"]["EntrepriseCourante"];
            entreprises: components["schemas"]["EntrepriseAccessible"][];
            permissions: string[];
            /** @enum {string} */
            portee: "ENTREPRISE" | "PLATEFORME" | "CAISSE";
            utilisateur?: components["schemas"]["ResumeUtilisateur"];
        };
        ReponseRafraichissement: {
            /** Format: uuid */
            entrepriseCourante?: string;
            entreprises: components["schemas"]["EntrepriseAccessible"][];
            jetonAcces?: string;
        };
        ResultatEmploye: {
            compteExistant: boolean;
            employe: components["schemas"]["EmployeResume"];
            motDePasseTemporaire?: string;
            pinTemporaire?: string;
        };
        ResultatPriseDeCaisse: {
            jetonAcces?: string;
            /** @enum {string} */
            statut: "CONNECTE" | "PIN_A_CHANGER";
        };
        ResumeCompte: {
            administrateurPlateforme: boolean;
            email?: string;
            /** Format: uuid */
            id: string;
            motDePasseAChanger: boolean;
            telephone?: string;
        };
        ResumeUtilisateur: {
            /** Format: uuid */
            id: string;
            nom: string;
            prenom: string;
        };
        RoleAttribuable: {
            attribuable: boolean;
            backOffice: boolean;
            code: string;
            touteLEntreprise: boolean;
        };
        SessionCaisseCourante: {
            nomCourt: string;
            permissions: string[];
            prenom: string;
            role: string;
            /** Format: uuid */
            utilisateurId: string;
        };
        StatutCode: {
            /** Format: date-time */
            expireLe: string;
            /** @enum {string} */
            statut: "EN_ATTENTE" | "UTILISE" | "EXPIRE";
        };
        ValidationAccordee: {
            /** Format: date-time */
            expireLe: string;
            /** Format: uuid */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    courant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppareilCourant"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    appairer: {
        parameters: {
            query?: never;
            header: {
                "X-Demande-Tonti": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeAppairage"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppareilCourant"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    prendre: {
        parameters: {
            query?: never;
            header: {
                "X-Demande-Tonti": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandePriseDeCaisse"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatPriseDeCaisse"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    personnel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilCaisse"][];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    changerPin: {
        parameters: {
            query?: never;
            header: {
                "X-Demande-Tonti": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeChangementPin"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatPriseDeCaisse"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    lister_3: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResultatsAppareilResume"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    genererCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeCodeAppairage"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeGenere"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    statutCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatutCode"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    annulerCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    renommer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeRenommageAppareil"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppareilResume"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    revoquer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    connecter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeConnexion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseConnexion"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    deconnecter: {
        parameters: {
            query?: never;
            header: {
                "X-Demande-Tonti": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    rafraichir: {
        parameters: {
            query?: never;
            header: {
                "X-Demande-Tonti": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DemandeRafraichissement"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseRafraichissement"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    moi_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCaisseCourante"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    renouveler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseJetonCaisse"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    validateurs: {
        parameters: {
            query: {
                permission: "COMMANDE_CREER" | "LIGNE_ANNULER_APRES_ENVOI" | "TABLE_TRANSFERER" | "REMISE_APPLIQUER" | "REMISE_AU_DELA_PLAFOND" | "ARTICLE_OFFRIR" | "PAIEMENT_ENCAISSER" | "PAIEMENT_REMBOURSER" | "CAISSE_OUVRIR" | "CAISSE_FERMER" | "CAISSE_MOUVEMENT" | "STOCK_RECEPTIONNER" | "STOCK_AJUSTER" | "CATALOGUE_GERER" | "PRIX_MODIFIER" | "RAPPORT_VENTES" | "RAPPORT_FINANCIER" | "CLIENT_CREDIT" | "PERSONNEL_GERER" | "ETABLISSEMENT_GERER" | "BACK_OFFICE" | "APPAREIL_GERER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilCaisse"][];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    valider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeValidation"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationAccordee"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    lister_2: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResultatsEtablissementResume"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    creer_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeEtablissement"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtablissementResume"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    modifier_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeModificationEtablissement"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtablissementResume"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    inscrire: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeInscription"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseConnexion"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    moi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseMoi"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    changerMotDePasse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeChangementMotDePasse"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    lister_1: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResultatsEmployeResume"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    creer_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeEmploye"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatEmploye"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeModificationEmploye"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatEmploye"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    desactiver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    reinitialiserPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatEmploye"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    reactiver_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    lister: {
        parameters: {
            query?: {
                page?: number;
                taille?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResultatsEntreprisePlateforme"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeCreationEntreprise"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntrepriseCreee"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    reactiver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    suspendre: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    configuration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationPublique"];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
    roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAttribuable"][];
                };
            };
            /** @description Erreur : voir « code » (IDENTIFIANTS_INVALIDES, ACCES_REFUSE, REQUETE_INVALIDE…) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseErreur"];
                };
            };
        };
    };
}
